### ISSUE TITLE
using getDashboardWidgetValue with more than one widget id doesn't work

### ISSUE THREAD

**Issue by mrbonezy** [kolomiichenko/graylog-api#9]
This is due to changing mPath and reusing it. (see index.js:28)

I've worked around it by recording the original mPath and setting it back after issuing the request.

**Comment by mautematico** [comment]
@shaharyakir  Could you please include steps to reproduce this issue?

As you seem to already found a workarround on this, It would be awesome if you can send a PR to get this fixed for everyone :)

**Comment by mrbonezy** [comment]
@mautematico this refers to an older version. From taking a look at the current committed index.js I can see that you've already resolved this issue by using `computedPath` instead of modifying the original `m.path`

**Comment by mautematico** [comment]
Awesome. 👍 

Then should this issue be closed. I can't close it, but sure an admin will do soon.
